#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: 26d5ab7ca0603023f487bf92427c9c45a0b3b3c5
    logging:
        logstash: # forward logs to ELK
            enabled: true
            host: internal-poc-monitoring-alb-01-914846118.ap-southeast-2.elb.amazonaws.com
    metrics:
        logs: # report metrics in the logs
            enabled: true
            report-frequency: 60 # in seconds
spring:
    zipkin:
        base-url: http://internal-poc-monitoring-alb-01-914846118.ap-southeast-2.elb.amazonaws.com:9411
        enabled: true

eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@internal-poc-eureka-alb-1634500355.ap-southeast-2.elb.amazonaws.com:8761/eureka/
