version: '2'
services:
    employeeops-app:
        image: employeeops
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://employeeops-postgresql:5432/employeeOps
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=employeeops-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=admin
    employeeops-postgresql:
        image: postgres:9.6.2
        environment:
            - POSTGRES_USER=employeeOps
            - POSTGRES_PASSWORD=
    employeeops-elasticsearch:
        image: elasticsearch:2.4.1
    
    portalemp-app:
        image: portalemp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://portalemp-postgresql:5432/portalEmp
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=portalemp-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 8080:8080
    portalemp-postgresql:
        image: postgres:9.6.2
        environment:
            - POSTGRES_USER=portalEmp
            - POSTGRES_PASSWORD=
    portalemp-elasticsearch:
        image: elasticsearch:2.4.1
    
    taskops-app:
        image: taskops
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://taskops-postgresql:5432/taskOps
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=taskops-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=admin
    taskops-postgresql:
        image: postgres:9.6.2
        environment:
            - POSTGRES_USER=taskOps
            - POSTGRES_PASSWORD=
    taskops-elasticsearch:
        image: elasticsearch:2.4.1
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry

    jhipster-elasticsearch:
        extends:
            file: jhipster-console.yml
            service: jhipster-elasticsearch
    jhipster-logstash:
        extends:
          file: jhipster-console.yml
          service: jhipster-logstash
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console
    jhipster-zipkin:
        extends:
            file: jhipster-console.yml
            service: jhipster-zipkin
