version: '2'
services:
    employeeops-app:
        image: employeeops
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://employeeops-postgresql:5432/employeeOps
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=employeeops-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=admin
    employeeops-postgresql:
        image: postgres:9.6.2
        environment:
            - POSTGRES_USER=employeeOps
            - POSTGRES_PASSWORD=
    employeeops-elasticsearch:
        image: elasticsearch:2.4.1
