version: '2'
services:
    taskops-app:
        image: taskops
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://taskops-postgresql:5432/taskOps
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=taskops-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=admin
    taskops-postgresql:
        image: postgres:9.6.2
        environment:
            - POSTGRES_USER=taskOps
            - POSTGRES_PASSWORD=
    taskops-elasticsearch:
        image: elasticsearch:2.4.1
